[package]
name = "pizero-gadget-gamepads"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
env_logger = "0.10.0"
log = "0.4.17"
gilrs = "0.10.2"
signal-hook = "0.3.15"
scroll = { version = "0.11.0", features = ["derive"] }
